default: &default
  adapter: postgresql
  encoding: unicode
  host: laa-crime-apply-mock-api-db
  database: laa-crime-apply-mock-api
  port: 5432
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default

production:
  <<: *default
  sslmode: <%= ENV.fetch('DATABASE_SSLMODE', 'verify-full') %>
  sslrootcert: <%= ENV['RDS_COMBINED_CA_BUNDLE'] %>
