default: &default
  adapter: postgresql
  encoding: unicode
  database: laa-crime-apply-mock-api
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { 'postgresql://postgres@postgres/laa-crime-apply-mock-api' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>

test:
  <<: *default

production:
  <<: *default
  sslmode: <%= ENV.fetch('DATABASE_SSLMODE', 'verify-full') %>
  sslrootcert: <%= ENV['RDS_COMBINED_CA_BUNDLE'] %>
