default: &default
  adapter: postgresql
  encoding: unicode
  database: laa-crime-apply-mock-api
  port: 5432
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { 'postgresql://postgres:postgres@localhost:5432/laa-crime-apply-mock-api' } %>

test:
  <<: *default

production:
  <<: *default
  sslmode: <%= ENV.fetch('DATABASE_SSLMODE', 'verify-full') %>
  sslrootcert: <%= ENV['RDS_COMBINED_CA_BUNDLE'] %>
