apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
