apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}
  labels:
    {{- include "laa-crime-apply-mock-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "laa-crime-apply-mock-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "laa-crime-apply-mock-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-crime-apply-mock-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          {{ include "laa-crime-apply-mock-api.env-vars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
    spec:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    serviceAccountName: {{ include "laa-crime-apply-mock-api.serviceAccountName" . }}
    securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
    containers:
      - name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "cimg/postgres:15.2"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.db.password }}
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: {{ .Values.db.dbname }}
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}