apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-crime-apply-mock-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "postgres:15.2-alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: {{ .Values.db.dbname }}
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}