apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}
  labels:
    {{- include "laa-crime-apply-mock-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laa-crime-apply-mock-api.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ include "laa-crime-apply-mock-api.fullname" . }}-db
