name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 #v4
    - uses: ruby/setup-ruby@v1 #v1
      with:
        ruby-version: '4.0.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install brakeman --version 6
    - run: brakeman
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
