name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 #v1
    - run: gem install brakeman --version 6
    - run: brakeman
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
